Software version paralel with full functional firemware.
jhu-cisst/mechatronics-software pull request #15
Opened 2021-07-15 08:41 UTC by qiguaiderenmen

2021-08-15 12:10 UTC, pkazanzides requested changes
Some cleanup/revision still needed.

2021-08-15 12:10 UTC, pkazanzides commented on lib/code/AmpIO.cpp
> +    // For DS2480B serial method, the approximate wait time is about 4-5 sec.
If the DS2480B wait time is 4-5 seconds, why are you only waiting 2 seconds?

2021-08-15 12:10 UTC, pkazanzides commented on lib/code/AmpIO.cpp
> +    if (useDS2480B) ctrl |= 4;  // corresponds to reg_wdata[2] in firmware
With the auto-detect feature, I don't think reg_wdata[2] is needed anymore

2021-08-15 12:10 UTC, pkazanzides commented on lib/code/AmpIO.cpp
> +        ctrl |= 1;
Why change this?

2021-08-15 12:10 UTC, pkazanzides commented on lib/code/AmpIO.cpp
> +        if (!DallasWriteControl(13)) return false;
Maybe use hex so the bit settings are more obvious?

2021-08-15 12:10 UTC, pkazanzides commented on tests/instrument.cpp
> -    if ((status & 0x00000001) != 0x00000001) {
Most of this code can be restored now.

2021-08-26 04:23 UTC, qiguaiderenmen commented on lib/code/AmpIO.cpp
> +    // For DS2480B serial method, the approximate wait time is about 4-5 sec.
4-5 seconds is the time in total for DS2480B. 2 seconds is for a single block read, say 256 bytes. We have 4*256 = 2048 bytes to read in total.

2021-08-26 04:23 UTC, qiguaiderenmen commented on tests/instrument.cpp
> -    if ((status & 0x00000001) != 0x00000001) {
THe interface enable thing is restored, but I don't think we still have those unexpected_idx things, maybe we should just remove them.

2021-08-26 04:23 UTC, qiguaiderenmen commented on lib/code/AmpIO.cpp
> +        if (!DallasWriteControl(13)) return false;
Sure, now hex and comments added

2021-08-26 04:23 UTC, qiguaiderenmen commented on lib/code/AmpIO.cpp
> +        ctrl |= 1;
No need indeed, change back and add comments.

2021-08-26 04:23 UTC, qiguaiderenmen commented on lib/code/AmpIO.cpp
> +    if (useDS2480B) ctrl |= 4;  // corresponds to reg_wdata[2] in firmware
Yes, and parallel modification made in firmware.

2021-08-26 04:33 UTC, pkazanzides commented on lib/code/AmpIO.cpp
> +    // For DS2480B serial method, the approximate wait time is about 4-5 sec.
O.K. But fix the comment.  It seems like a bug if you say to wait up to 2000 msec but then say that the wait time is 4-5 sec.

2021-08-26 04:59 UTC, qiguaiderenmen commented on lib/code/AmpIO.cpp
> +    // For DS2480B serial method, the approximate wait time is about 4-5 sec.
That's true. Hopefully now the comment looks better.

2021-08-26 05:15 UTC, merged